### ISSUE TITLE
extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0"

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/sponsor-token-website#1]
- 第一個修正方法
目前已經將 webpack 的版本升到 4.0 了
所以照 extract-text-webpack-plugin 官方的說詞
https://github.com/webpack-contrib/extract-text-webpack-plugin
需要換成 mini-css-extract-plugin

- 第二個修正方法
全部降回 webpack 3

- 第三個修正方法
用到的地方做個替換

**Comment by lychees** [comment]
Solution 1 sounds better.

**Comment by yukiexe** [comment]
目前整個是回頭用 webpack 3 ，基於其他莫名的bug
所以問題解決了
